server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/masterkapyshop
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
    outputChangeLogFile: src/main/resources/liquibase-outputChangeLog.xml
    changeLogFile: src/main/resources/liquibase-outputChangeLog.xml
    referenceUrl: hibernate:spring:com.example.kapyedu?dialect=org.hibernate.dialect.PostgreSQLDialect
    diffChangeLogFile: src/main/resources/liquibase-diff-changeLog.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
multitenancy:
  schema-cache:
    maximumSize: 100
    expireAfterAccess: 10
  tenant:
    repository:
      packages: com.example.kapyedu.repository
    entityManager:
      packages: com.example.kapyedu.domain
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.xml
  master:
    repository:
      packages: com.example.kapyedu.multitenancy.repository
    entityManager:
      packages: com.example.kapyedu.multitenancy.domain
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.xml
